name: Docker build and push to DockerHub

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ssakharov
          password: secrets.anaconda-uncurious-permit
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ssakharov/network-tools-v2:latest



#name: Docker Image CI
#
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

#jobs:

#  build:

 #   runs-on: ubuntu-latest
#
  #  steps:
 #   - uses: actions/checkout@v2
   # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag network-tools-v2:$(date +%s)
#      run: docker login -u ssakharov -p anaconda-uncurious-permit docker.io
#      run: docker push ssakharov/network-tools:latest
